<div class="content">
    <article>
        <h3>Está visitando el sito web de Antoine Lambert, estudiante de IMT Nord Europe.</h3>
        <p>PHP es un lenguaje de scripting que se utiliza sobre todo en el lado del servidor: en esta arquitectura, el servidor interpreta el código PHP de las páginas web solicitadas y genera código (por ejemplo, HTML, XHTML, CSS) y datos (por ejemplo, JPEG, GIF, PNG) que pueden ser interpretados y renderizados por un navegador web. PHP también puede generar otros formatos como WML, SVG y PDF.</p>
        <p>Se diseñó para permitir la creación de aplicaciones dinámicas, en su mayoría desarrolladas para la Web. PHP se acopla con mayor frecuencia a un servidor Apache, aunque puede instalarse en la mayoría de los servidores HTTP, como IIS o nginx. Este acoplamiento permite recuperar información de una base de datos, de un sistema de archivos (contenidos de archivos y árboles) o simplemente datos enviados por el navegador para ser interpretados o almacenados para su uso posterior.</p>
        <p>Es un lenguaje no tipado y flexible y, por tanto, fácil de aprender por un principiante pero, como resultado, pueden aparecer rápidamente agujeros de seguridad en las aplicaciones. Pragmático, PHP no se preocupa por la teoría y tiende a elegir el camino más directo. Sin embargo, los nombres de las funciones (y el paso de los argumentos) no siempre siguen una lógica uniforme, lo que puede ser perjudicial para el aprendizaje.</p>
        <p>Su uso comienza con el tratamiento de los formularios y luego con el acceso a las bases de datos. El acceso a las bases de datos es fácil una vez instalados los módulos correspondientes en el servidor. El punto fuerte más evidente de este lenguaje es que, con el tiempo, ha permitido resolver fácilmente problemas antes complicados, por lo que se ha convertido en un componente esencial de las ofertas de alojamiento.</p>
        <p>Es multiplataforma: tanto en Linux como en Windows, permite reproducir fácilmente el mismo código en un entorno más o menos similar (aunque hay que tener en cuenta las reglas del árbol de directorios, que pueden cambiar).</p>
        <p>Es gratuito, fácil de usar e instalar, pero como cualquier otro lenguaje de programación, requiere una buena comprensión de las principales funciones comunes y un conocimiento agudo de las cuestiones de seguridad relacionadas con este lenguaje.</p>
        <p>La versión 5.3 introdujo muchas novedades: Namespace - un elemento fundamental en el desarrollo de extensiones, bibliotecas y marcos estructurados, funciones anónimas, cierres, etc.</p>
        <p>En 2018, casi el 80% de los sitios web utilizan PHP en sus distintas versiones.</p>
        <p>Desde hace varios años, el lenguaje PHP es objeto de encuentros nacionales organizados por la AFUP (Asociación Francesa de Usuarios de PHP), en los que se reúnen expertos en programación e industria para hablar de PHP y sus desarrolladores. La asociación organiza dos grandes eventos : el "Foro PHP", normalmente a finales de año, y las "Jornadas AFUP", que se celebran durante el primer semestre del año, simultáneamente en varias ciudades.</p>
    </article>
</div>
