<div class="content">
    <article>
        <h3>You are currently on the website of Antoine Lambert, student at IMT Nord Europe.</h3>
        <p>PHP is a scripting language used most often on the server side: in this architecture, the server interprets the PHP code of the requested web pages and generates code (e.g. HTML, XHTML, CSS) and data (e.g. JPEG, GIF, PNG) that can be interpreted and rendered by a web browser. PHP can also generate other formats such as WML, SVG and PDF.</p>
        <p>It was designed to allow the creation of dynamic applications, most often developed for the Web. PHP is most often coupled with an Apache server although it can be installed on most HTTP servers such as IIS or nginx. This coupling allows to retrieve information from a database, a file system (file and tree contents) or simply data sent by the browser to be interpreted or stored for later use.</p>
        <p>It is a language that is not very typed and flexible and therefore easy to learn by a beginner but, as a result, security flaws can quickly appear in applications. Pragmatic, PHP does not bother with theory and tends to choose the most direct path. Nevertheless, the names of the functions (as well as the passing of arguments) do not always follow a uniform logic, which can be detrimental to learning.</p>
        <p>Its use begins with the processing of forms and then with access to databases. Access to the databases is easy once the corresponding modules have been installed on the server. The most obvious strength of this language is that over time it has made it possible to easily solve previously complicated problems and has therefore become an essential component of hosting offers.</p>
        <p>It is multi-platform: on Linux as well as on Windows it allows easily to reproduce the same code on a more or less similar environment (although you have to take into account the directory tree rules, which can change).</p>
        <p>This language is free, easy to use and to install, but like any programming language, it requires a good understanding of the main common functions as well as an acute knowledge of the security issues related to this language.</p>
        <p>Version 5.3 introduced many new features: namespaces - a fundamental element in the development of extensions, libraries and structured frameworks, anonymous functions, closures, etc.</p>
        <p>In 2018, nearly 80% of websites use PHP in its various versions.</p>
        <p>For several years now, the PHP language has been the subject of national gatherings organized by the AFUP (the French Association of PHP Users), where experts in programming and in the field meet to discuss PHP and its developers. The association organizes two major events : the "PHP Forum", usually at the end of the year, and the "AFUP Days", which take place during the first semester, simultaneously in several cities.</p>
    </article>
</div>
